/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BossControlPanel: typeof import('./src/components/BossControlPanel.vue')['default']
    BossInfo: typeof import('./src/components/BossInfo.vue')['default']
    BossInfoItem: typeof import('./src/components/BossInfoItem.vue')['default']
    BossStatusButton: typeof import('./src/components/BossStatusButton.vue')['default']
    ChannelCard: typeof import('./src/components/ChannelCard.vue')['default']
    ChannelOverview: typeof import('./src/components/ChannelOverview.vue')['default']
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    RecommendedChannels: typeof import('./src/components/RecommendedChannels.vue')['default']
    RecommendedSection: typeof import('./src/components/RecommendedSection.vue')['default']
    RecordHistory: typeof import('./src/components/RecordHistory.vue')['default']
    RecordItem: typeof import('./src/components/RecordItem.vue')['default']
    RoomManager: typeof import('./src/components/RoomManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    ToggleDarkThemeButton: typeof import('./src/components/ToggleDarkThemeButton.vue')['default']
  }
}
