/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BossControlPanel: typeof import('./src/components/BossControlPanel.vue')['default']
    BossInfo: typeof import('./src/components/BossInfo.vue')['default']
    BossInfoItem: typeof import('./src/components/BossInfoItem.vue')['default']
    BossStatusButton: typeof import('./src/components/BossStatusButton.vue')['default']
    ChannelCard: typeof import('./src/components/ChannelCard.vue')['default']
    ChannelOverview: typeof import('./src/components/ChannelOverview.vue')['default']
    CountdownTimer: typeof import('./src/components/CountdownTimer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GoogleLoginButton: typeof import('./src/components/GoogleLoginButton.vue')['default']
    MaintenanceBanner: typeof import('./src/components/MaintenanceBanner.vue')['default']
    RecommendedChannels: typeof import('./src/components/RecommendedChannels.vue')['default']
    RecommendedSection: typeof import('./src/components/RecommendedSection.vue')['default']
    RecordHistory: typeof import('./src/components/RecordHistory.vue')['default']
    RecordItem: typeof import('./src/components/RecordItem.vue')['default']
    RoomManager: typeof import('./src/components/RoomManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
