services:
  boss_service:
    build:
      context: backend
    image: ${REMOTE_REGISTRY_IP}/boss_service/boss_service:${VERSION}
    platform: linux/arm64  # 構建適配 ARM 的镜像
    container_name: boss_service
    ports:
      - "1254:1254"
    command: uvicorn main:app --host 0.0.0.0 --port 1254 --root-path /api
    volumes:
      - ./.env:/boss-tracker/.env
    restart: always

  boss_tracker_nginx:
    build:
      context: ./frontend
    platform: linux/arm64  # 構建適配 ARM 的镜像
    image: ${REMOTE_REGISTRY_IP}/boss_service/boss_tracker_nginx:${VERSION}
    container_name: boss_tracker_nginx
    ports:
      - "2255:80"
