"""Finalize BossType and BossRecord models

Revision ID: 12ca3a9fc49c
Revises: 7a0ebabd50b1
Create Date: 2025-09-10 16:07:23.322736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ca3a9fc49c'
down_revision: Union[str, Sequence[str], None] = '7a0ebabd50b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_room_users_room'), table_name='room_users_old')
    op.drop_table('room_users_old')
    op.create_index('idx_boss_records_room_boss_type', 'boss_records', ['room_id', 'boss_type_id'], unique=False)
    op.create_foreign_key(None, 'boss_records', 'boss_types', ['boss_type_id'], ['id'])
    op.alter_column('boss_types', 'name_en',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('boss_types', 'name_zh',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'boss_types', ['name_en'])
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('idx_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.drop_index(op.f('idx_room_users_anonymous_session'), table_name='room_users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_google_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_room_users_anonymous_session'), 'room_users', ['anonymous_session_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'boss_types', type_='unique')
    op.alter_column('boss_types', 'name_zh',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('boss_types', 'name_en',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'boss_records', type_='foreignkey')
    op.drop_index('idx_boss_records_room_boss_type', table_name='boss_records')
    op.create_table('room_users_old',
    sa.Column('room_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_session', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('room_users_room_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_session', name=op.f('room_users_pkey'))
    )
    op.create_index(op.f('idx_room_users_room'), 'room_users_old', ['room_id'], unique=False)
    # ### end Alembic commands ###
