"""add composite indexes for room state and history queries

Revision ID: 1ec3f4f2eb9a
Revises: d79b444d59c1
Create Date: 2026-04-23 18:22:49.860922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec3f4f2eb9a'
down_revision: Union[str, Sequence[str], None] = 'd79b444d59c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_boss_records_room_history', 'boss_records', ['room_id', 'id'], unique=False)
    op.create_index('idx_boss_records_room_latest', 'boss_records', ['room_id', 'channel', 'boss_type_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_boss_records_room_latest', table_name='boss_records')
    op.drop_index('idx_boss_records_room_history', table_name='boss_records')
    # ### end Alembic commands ###
