"""add room_id to boss_types for custom bosses

Revision ID: 254aad421293
Revises: d04f4ccc4254
Create Date: 2026-04-17 17:29:10.970144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254aad421293'
down_revision: Union[str, Sequence[str], None] = 'd04f4ccc4254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_types', sa.Column('room_id', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('boss_types_name_en_key'), 'boss_types', type_='unique')
    op.create_foreign_key(None, 'boss_types', 'rooms', ['room_id'], ['room_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boss_types', type_='foreignkey')
    op.create_unique_constraint(op.f('boss_types_name_en_key'), 'boss_types', ['name_en'], postgresql_nulls_not_distinct=False)
    op.drop_column('boss_types', 'room_id')
    # ### end Alembic commands ###
