"""Add webhook fields and celery task ids

Revision ID: 4a81028b3abb
Revises: 12ca3a9fc49c
Create Date: 2026-04-14 10:33:48.406687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a81028b3abb'
down_revision: Union[str, Sequence[str], None] = '12ca3a9fc49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_records', sa.Column('celery_task_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('discord_webhook_url', sa.String(length=1000), nullable=True))
    op.add_column('rooms', sa.Column('webhook_alert_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'webhook_alert_type')
    op.drop_column('rooms', 'discord_webhook_url')
    op.drop_column('boss_records', 'celery_task_ids')
    # ### end Alembic commands ###
