"""add last_cleared_at to rooms

Revision ID: c5d6a00c51f1
Revises: ef3c52d29dd0
Create Date: 2026-06-03 14:21:32.238627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5d6a00c51f1'
down_revision: Union[str, Sequence[str], None] = 'ef3c52d29dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('last_cleared_at', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'last_cleared_at')
    # ### end Alembic commands ###
