"""remove room_users table

Revision ID: d04f4ccc4254
Revises: d096836f36ba
Create Date: 2026-04-17 17:04:13.377447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd04f4ccc4254'
down_revision: Union[str, Sequence[str], None] = 'd096836f36ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_room_users_room_id'), table_name='room_users')
    op.drop_index(op.f('idx_room_users_user_id'), table_name='room_users')
    op.drop_table('room_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('anonymous_session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('user_id IS NOT NULL OR anonymous_session_id IS NOT NULL', name=op.f('chk_user_or_anonymous')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('room_users_room_id_fkey1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('room_users_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('room_users_pkey1')),
    sa.UniqueConstraint('room_id', 'anonymous_session_id', name=op.f('room_users_room_anonymous_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('room_id', 'user_id', name=op.f('room_users_room_user_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_room_users_user_id'), 'room_users', ['user_id'], unique=False)
    op.create_index(op.f('idx_room_users_room_id'), 'room_users', ['room_id'], unique=False)
    # ### end Alembic commands ###
