"""add webhook toggle events

Revision ID: d096836f36ba
Revises: 4a81028b3abb
Create Date: 2026-04-14 17:56:14.742396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd096836f36ba'
down_revision: Union[str, Sequence[str], None] = '4a81028b3abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('discord_webhook_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rooms', sa.Column('webhook_notify_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'webhook_notify_events')
    op.drop_column('rooms', 'discord_webhook_enabled')
    # ### end Alembic commands ###
