"""boss_records_boss_type_id_cascade_delete

Revision ID: d79b444d59c1
Revises: 202ad761d3fc
Create Date: 2026-04-17 18:08:06.888311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79b444d59c1'
down_revision: Union[str, Sequence[str], None] = '202ad761d3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('boss_records_boss_type_id_fkey'), 'boss_records', type_='foreignkey')
    op.create_foreign_key(None, 'boss_records', 'boss_types', ['boss_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boss_records', type_='foreignkey')
    op.create_foreign_key(op.f('boss_records_boss_type_id_fkey'), 'boss_records', 'boss_types', ['boss_type_id'], ['id'])
    # ### end Alembic commands ###
