"""add feedback items and votes

Revision ID: ef3c52d29dd0
Revises: 1ec3f4f2eb9a
Create Date: 2026-06-01 11:55:54.748800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3c52d29dd0'
down_revision: Union[str, Sequence[str], None] = '1ec3f4f2eb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'open', 'planning', 'done', 'rejected')", name='check_feedback_status'),
    sa.CheckConstraint("type IN ('bug', 'feature')", name='check_feedback_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_items_created_by', 'feedback_items', ['created_by'], unique=False)
    op.create_index('idx_feedback_items_status_created', 'feedback_items', ['status', 'created_at'], unique=False)
    op.create_table('feedback_votes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'user_id', name='uq_feedback_vote_user')
    )
    op.create_index('idx_feedback_votes_feedback', 'feedback_votes', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_votes_feedback', table_name='feedback_votes')
    op.drop_table('feedback_votes')
    op.drop_index('idx_feedback_items_status_created', table_name='feedback_items')
    op.drop_index('idx_feedback_items_created_by', table_name='feedback_items')
    op.drop_table('feedback_items')
    # ### end Alembic commands ###
