name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  HARBOR: ${{ secrets.HARBOR_URL }}
  IMAGE_BACKEND: ${{ secrets.HARBOR_URL }}/boss_service/boss_service
  IMAGE_FRONTEND: ${{ secrets.HARBOR_URL }}/boss_service/boss_timer_nginx

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU（arm64 支援）
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:${{ github.sha }}
            ${{ env.IMAGE_BACKEND }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_BACKEND }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_BACKEND }}:cache,mode=max

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend     # 你的 frontend Dockerfile 位置
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
            ${{ env.IMAGE_FRONTEND }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_FRONTEND }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_FRONTEND }}:cache,mode=max

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: ~/boss-tracker/deploy.sh ${{ github.sha }}